feat: enhance CI/CD pipeline with coverage checks, vulnerability scans, and smoke tests

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -36,7 +36,16 @@ jobs:
 
       - name: Run Unit Tests
         run: |
-          go test -v -race -cover ./...
+          go test -v -race -cover -coverprofile=coverage.out ./internal/handlers/...
+
+          TCOVERAGE=$(go tool cover -func=coverage.out | grep total | grep | awk '{print substr($3, 1, length($3)-1)}')
+          echo "Total Coverage is $TOTAL_COVERAGE%"
+
+          if (( $(echo "$TOTAL_COVERAGE < 80.0" | bc -l) )); then
+            echo "Test coverage ($TOTAL_COVERAGE%) is below the 80% threshold."
+            exit 1
+          fi
+          echo "Test coverage ($TOTAL_COVERAGE%) is acceptable."
 
       # - name: Run Integration Tests
       #   env:
@@ -101,6 +110,33 @@ jobs:
           go install github.com/securego/gosec/v2/cmd/gosec@latest
           gosec ./...
 
+  integration-sca:
+    name: SCA Analysis
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@master
+        with:
+          scan-type: "fs"
+          scan-ref: "."
+          ignore-unfixed: true
+          format: "table"
+          severity: "CRITICAL,HIGH"
+          exit-code: "1"
+
+  integration-iac-scan:
+    name: IaC Security Scan
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - name: Scan k8s directory
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          directory: k8s/
+          framework: kubernetes
+          soft_fail: false #
+
   delivery:
     name: Build Docker Image (Delivery)
     needs:
@@ -142,6 +178,15 @@ jobs:
             elapsed=$((elapsed + 2))
           done
           echo "Container is healthy!"
+
+      - name: Scan Docker Image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: "github-api-manager:latest"
+          format: "table"
+          exit-code: "1" # if critical issues are found - break
+          ignore-unfixed: true
+          severity: "CRITICAL,HIGH"
 
       - name: Show Container logs on failure
         if: failure()
@@ -189,3 +234,17 @@ jobs:
         run: |
           kubectl get pods
           kubectl get services
+
+      - name: Run Smoke Tests against Minikube
+        run: |
+          echo "Starting smoke tests..."
+          SERVICE_URL=$(minikube service scalabit-challenge-api --url)
+          echo "Testing endpoint: $SERVICE_URL/health"
+
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --retry 5 --retry-delay 5 --retry-connrefused $SERVICE_URL/health)
+
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "Smoke test failed! HTTP Status: $HTTP_STATUS"
+            exit 1
+          fi
+          echo "Smoke test passed! Application is live and healthy."
